server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.66.66
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI5tFBaYUHoKQgRb9WBh6Q # 你自己的accessKeyId
    accessKeySecret: 3C0O08ZofUcSXx3xSYkk8Bc7zd0uc4 # 你自己的AccessKeySecret
    signName: 阿里云短信测试 # 签名名称
    verifyCodeTemplate: SMS_154950909 # 模板名称